Compare the entry files hash to speed up the config phase
Klebert-Engineering/zserio-cmake-helper pull request #4
Opened 2023-10-05 15:16 UTC by johannes-wolf

This change speeds up project regeneration by computing the SHA1 of the entry zserio file and comparing it against the SHA1 of the last zserio cpp generation run. In addition, zserio gets downloaded only if the zip is missing locally.

2023-10-13 14:49 UTC, MisterGC requested changes, later dismissed
This really helps - for me it was 2sec -> 0.1sec for a medium schema - but where is the `CACHE_GENERATION` option. Have I missed something?

2023-10-13 16:24 UTC, johannes-wolf commented
> This really helps - for me it was 2sec -> 0.1sec for a medium schema - but where is the `CACHE_GENERATION` option. Have I missed something?

I forgot to push the latest commit. Now it is there.

2023-10-17 17:42 UTC, josephbirkner commented
Tested with livesource, works well 👍

2023-10-17 17:42 UTC, josephbirkner approved these changes

2023-10-17 17:43 UTC, merged